### PR TITLE
feature: Add archive gallery-list page

### PR DESCRIPTION
**Pull request by euije**
## What is this PR do?
- `Introduction`: Implementation Gallery-List Page
- `Notion Ticket`: [notion link](https://www.notion.so/osds--/FE-archive-list-87efd666c2684ab8bc2c94a90cbe8fbd)

## Changes
- [x] : Rename directories of images
- [x] : Rename directories of fonts
- [x] : Set Mobile-Dom (margin-left/right : 24px)
- [x] : Represent Time Format by cases

## Bugs
- [ ] : (!)Searching words with 'tag' and 'title' at the same time, it doubles.
- [ ] : Have to resize the search-bar

## After To-do
- [ ] : Implement Sorting Feature
- [ ] : Make background img save ratio
- [ ] : Make float-button at the right-bottom
- [ ] : Link Routes to Album-Specific Pages

## Screenshot
ezgif com-gif-maker (1)
ezgif com-gif-maker (2)

### CODE REVIEW

**Comment by hi-there-insahae** [comment]
우와.... 역시 리신 믿음직스롭네요 ㅎㅎ

**Review by unanchoi — COMMENTED** [review]
앞에 커밋과 분리하지 않았어도 괜찮을 것 같아요!

**Comment by unanchoi** [comment]
머지 하겠습니다!

**Comment by euije** [comment]
#bugs-1 : https://github.com/NodabFamily/OSDS-client/issues/9

**Pull request merged**
